<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Recipe upload</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            table {
				 color: #333;
                font-family: 'Lato', sans-serif;
            }
			
			table tr td{
				vertical-align:middle;
			}
        </style> 
		

		<script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		 <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		 <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.10.0/js/lightbox.min.js"  crossorigin="anonymous"></script>
		<link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.10.0/css/lightbox.min.css" rel="stylesheet" crossorigin="anonymous" />
		
		<script>
			jQuery( document ).ready(function($) {
				$('.delete_recipe').click(function(e){
					e.preventDefault();
					
					
					settings = {		
						type: "POST",
						url: 'https://org100h.myshopify.com/apps/recipe/delete'
					}
					settings.data = {
						key: $(this).data('key'),
						order: $(this).data('order'),
						name: $(this).data('name')
					}
					
					$.ajax(settings).done(function (response) {
							console.log(response);
						});
					
				});
			});
		</script>
    </head>
    <body><div class="table-responsive">
	<table class="table table-sm ">
	
	
	   <?php 
	   
	   
	   foreach ($orders as $order) {  ?>
		
		<tr>
			<td><?php  echo $order->name; ?></td>
			<td>
				<div id="accordion">
				<?php foreach($order->line_items as $items){ ?>
				
					<div id="heading-<?php  echo $items->id; ?>">
					
						<a href="#" class="item-link" data-toggle="collapse" data-target="#item-<?php  echo $items->id; ?>" aria-expanded="true" aria-controls="item-<?php  echo $items->id; ?>">
						  <?php  echo $items->title; ?>
						</a>
					 
					</div>

					<div id="item-<?php  echo $items->id; ?>" class="collapse" aria-labelledby="heading-<?php  echo $items->id; ?>" data-parent="#accordion">
					
						<ul class="list-group"  >	
							<li class="list-group-item" ><strong>id:</strong> <?php  echo $items->id; ?></li>
							<li class="list-group-item" ><strong>sku:</strong> <?php  echo $items->sku; ?></li>
							<li class="list-group-item" ><strong>vendor:</strong> <?php  echo $items->vendor; ?></li>
						</ul>	
					  
					</div>
				  
				
				
						
				<?php } ?>
				</div>
			
				</td>
			<td><?php  echo $order->contact_email; ?></td>
			<td> <?php  foreach($order->note_attributes as $note  ){ ?>
				<a data-lightbox="<?php echo $note->name   ?>" data-title="<?php echo $note->name ?>" href="<?php echo $note->value   ?>"> <?php echo $note->name   ?></a>
				<a href="#" class="delete_recipe text-danger" data-name="<?php echo $note->name ?>" data-order="<?php  echo $order->id; ?>" data-key="<?php echo basename($note->value) ?>" >Delete</a>
				
			<?php }	?></td>
			
		</tr>

	   <?php } ?>

	   </table></div>
    </body>
</html>
